// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          int32
	Title       string
	Description pgtype.Text
	Status      pgtype.Text
	UserID      pgtype.Int4
}

type User struct {
	ID    int32
	Name  string
	Email string
}
